
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_21
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_48

#define AUDIO_CODEC_PA_PIN GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_38
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_47
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_17
#define BOOT_BUTTON_GPIO GPIO_NUM_1
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_18
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_2
#define CHARGING_GPIO GPIO_NUM_41
#define DONE_GPIO GPIO_NUM_42

#define RESET_NVS_BUTTON_GPIO GPIO_NUM_NC
#define RESET_FACTORY_BUTTON_GPIO GPIO_NUM_NC

#define BATTERY_ADC_PIN GPIO_NUM_3

// SSD1306 OLED I2C 引脚配置
#define DISPLAY_SDA_PIN GPIO_NUM_15
#define DISPLAY_SCL_PIN GPIO_NUM_16

// SSD1306 屏幕分辨率 128x64
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false

#define LIGHT_RX_PIN GPIO_NUM_12
#define LIGHT_TX_PIN GPIO_NUM_13

#define PWM_LED_GPIO GPIO_NUM_NC

#define PWM_LED_UART_TX_PIN GPIO_NUM_NC
#define PWM_LED_UART_RX_PIN GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
